name: "godot-ci export"
on: 
  push: 
    branches: 
      - deploy

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: Dubious Arcade

jobs:
  deploy-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:mono-3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p build/web ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/templates/${GODOT_VERSION}.stable.mono
      - name: Web Build
        run: godot -v --export "HTML5" ./build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: ./build/web/
      - name: Itch.io
        env: 
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: butler push ./build/web ${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAME }}:web
